### ISSUE TITLE
[Quest][Camp Narache] Our Tribe Imprisoned 

### ISSUE THREAD

**Issue by Kyyteo** [FlamestrikeGG/Bugtracker-Flamestrike#1]
Description: Captured Braves Behaving incorrectly

Current Behavior (The current behavior of the reported function): Captured Braves upon opening the cage will do their say, then sometimes exit the cage or sometimes walk around inside of it.

Expected behavior (The correct behavior of the reported function): Upon the cage being opened, the Captured Brave is supposed to run out, do their say, then run off before fading. 

How to reproduce the bug (How did this happen?): Take the quest then go free a brave.

https://youtu.be/5TzJnb0vZVo?t=58
https://cata-shoot.tauri.hu/?quest=24852

**Comment by LKArthas** [comment]
Fixed
