### ISSUE TITLE
[NPC] Spirit healer missing - Borean Tundra

### ISSUE THREAD

**Issue by Sevenity-dot** [FlamestrikeGG/Bugtracker-Flamestrike#13]
Current Behavior (The current behavior of the reported function): Spirit healer missing in Valiance Keep

Expected behavior (The correct behavior of the reported function): Should be spawned

How to reproduce the bug (How did this happen?): Visit the area and die

**Comment by FlamestrikeGG** [comment]
Fixed on newest rev
