### ISSUE TITLE
[Spell] Autolearn mount

### ISSUE THREAD

**Issue by Sevenity-dot** [FlamestrikeGG/Bugtracker-Flamestrike#14]
Current Behavior (The current behavior of the reported function): Currently as a Paladin/Warlock you don't get mount auto-learned at level 20

Expected behavior (The correct behavior of the reported function): Should have mount auto learned

How to reproduce the bug (How did this happen?): Get to level 20 as paladin/warlock

**Comment by FlamestrikeGG** [comment]
Fixed on newest rev
