### ISSUE TITLE
[NPC] Northwatch Scout

### ISSUE THREAD

**Issue by Kyyteo** [FlamestrikeGG/Bugtracker-Flamestrike#18]
Current Behavior (The current behavior of the reported function): Northwatch Scout has a 100% chance to drop a bag.

Expected behavior (The correct behavior of the reported function): Each bag should only have 1% chance to drop a bag.

How to reproduce the bug (How did this happen?): Kill a Northwatch Scout, and loot it.

https://cata-shoot.tauri.hu/?npc=39317

**Comment by FlamestrikeGG** [comment]
Should be fixed on next rev.
