### ISSUE TITLE
[Quest][The Ebon Hold] In Service of the Lich King

### ISSUE THREAD

**Issue by Kyyteo** [FlamestrikeGG/Bugtracker-Flamestrike#19]
Current Behavior (The current behavior of the reported function): Upon taking the quest, the Lich King does not start his speech

Expected behavior (The correct behavior of the reported function): When you start the quest, the Lich King should make a speech that the player can audibly hear.

How to reproduce the bug (How did this happen?): Take the quest.

https://www.youtube.com/watch?v=CMjLHi8p4kg
https://cata-shoot.tauri.hu/?npc=25462

**Comment by FlamestrikeGG** [comment]
Should be fixed on next rev.
