### ISSUE TITLE
[NPC] Adana Thunderhorn

### ISSUE THREAD

**Issue by Kyyteo** [FlamestrikeGG/Bugtracker-Flamestrike#2]
Description: Odd behavior when getting quests.

Current Behavior (The current behavior of the reported function): Upon getting the quests, Rite of Courage ( https://cata-shoot.tauri.hu/?quest=14456 ) and Stop the Thorncallers ( https://cata-shoot.tauri.hu/?quest=14455 ) Adana Thunderhorn still displays a yellow ! instead of a grey ?  She also shows a yellow ! on the minimap

Expected behavior (The correct behavior of the reported function): Upon getting these two quests, she should show a grey ? to show the quests are in progress. She shouldn't have a yellow ! again until you finish those two quests, at which point you can take on the next two quests in the chain.

How to reproduce the bug (How did this happen?): Start a Tauren, do the opening scenario until you get to the point where you can accept these quests from her.

**Comment by LKArthas** [comment]
Fixed
