### ISSUE TITLE
[Quest][The Ebon Hold] The Endless Hunger

### ISSUE THREAD

**Issue by Kyyteo** [FlamestrikeGG/Bugtracker-Flamestrike#20]
Current Behavior (The current behavior of the reported function): One of the says that Unworthy Initiate says has invalid data. Right now it displays "Sate your hunger on cold steel, $R" 

Expected behavior (The correct behavior of the reported function): I do believe that it's supposed to say your name in place of $R

How to reproduce the bug (How did this happen?): Take the quest, then keep unlocking cages until you get the voice line.

https://cata-shoot.tauri.hu/?npc=29567

**Comment by FlamestrikeGG** [comment]
Should be fixed on next rev.
