### ISSUE TITLE
[NPC] Havenshire Stallion

### ISSUE THREAD

**Issue by Kyyteo** [FlamestrikeGG/Bugtracker-Flamestrike#29]
Current Behavior (The current behavior of the reported function): Stallions are set as hostile to the other horses, so they all just gang up on each other.

Expected behavior (The correct behavior of the reported function): All the horses should be in the same faction

How to reproduce the bug (How did this happen?): Watch the smackdown of the century.

https://cata-shoot.tauri.hu/?npc=28605

**Comment by FlamestrikeGG** [comment]
Should be fixed on next rev.
