### ISSUE TITLE
[NPC] Bristleback Gun Thief

### ISSUE THREAD

**Issue by Kyyteo** [FlamestrikeGG/Bugtracker-Flamestrike#3]
Current Behavior (The current behavior of the reported function): Bristleback Gun Thief just stands there... (menacingly)

Expected behavior (The correct behavior of the reported function): Gun Thiefs are supposed to have a small patrol, and occasionally fire off their rifles

How to reproduce the bug (How did this happen?): Observe them

https://cata-shoot.tauri.hu/?npc=36708
https://youtu.be/zFQzHeEV7rk?t=91

**Comment by LKArthas** [comment]
Fixed
