### ISSUE TITLE
[Quest][Coldridge Valley] Give 'em What-For

### ISSUE THREAD

**Issue by iroflu** [FlamestrikeGG/Bugtracker-Flamestrike#33]
### Current Behavior:
Rockjaw Goons are showing as quest-givers for this quest. Cannot talk to them, but have icons above their head, and on mini-map.

### Expected behavior:
Rockjaw Goons are meant to be killed for the quest, should not show as quest giver.
The only quest-giver should be [Joren Ironstock](https://www.wowhead.com/npc=37081/joren-ironstock)

### How to reproduce the bug:
Finish the previous quest, then do not accept this quest. Look at mini-map and nearby Rockjaw Goons in distance.

https://www.wowhead.com/npc=37073/rockjaw-goon
https://www.wowhead.com/quest=24470/give-em-what-for
https://www.youtube.com/watch?v=kQmXoy7Feeg

**Comment by FlamestrikeGG** [comment]
@iroflu - Should be fixed now. Can you test and confirm that it works now?

**Comment by LKArthas** [comment]
Fixed
