### ISSUE TITLE
[Quest][Coldridge Valley] Don't Forget About Us

### ISSUE THREAD

**Issue by iroflu** [FlamestrikeGG/Bugtracker-Flamestrike#39]
### Current Behavior:
Quest is immediately considered completed and becomes "Click-To-Complete"

### Expected behavior:
Quest should be turned in directly to [Tharek Blackstone](https://www.wowhead.com/npc=1872/tharek-blackstone), not "Click-To-Complete"

### How to reproduce the bug:
Accept the quest, then check quest log to complete it.

https://www.wowhead.com/quest=24493/dont-forget-about-us

**Comment by FlamestrikeGG** [comment]
@iroflu - Should be fixed now. Can you test and confirm that it works now?

**Comment by LKArthas** [comment]
Fixed - Need to delete cache
