### ISSUE TITLE
[Quest][Camp Narache] Consecrated Note

### ISSUE THREAD

**Issue by Kyyteo** [FlamestrikeGG/Bugtracker-Flamestrike#4]
Current Behavior (The current behavior of the reported function): Quest puts a Consecrated Note in your inventory, and upon reading it, it says Item Page Missing

Expected behavior (The correct behavior of the reported function):  Upon reading the note, it should say

I have been awaiting your arrival, sunwalker. Chief Hawkwind himself told me of your interest in our order and I have agreed to begin your training. Please meet with me in the circle at the center of Camp Narache when you are ready to begin your instruction.

Sunwalker Helaku

How to reproduce the bug (How did this happen?): Take the quest and try to read the note.

https://cata-shoot.tauri.hu/?quest=27015
https://cata-shoot.tauri.hu/?item=60752
https://www.wowhead.com/item=60752/consecrated-note

**Comment by LKArthas** [comment]
Fixed
