### ISSUE TITLE
[NPC][Kharanos] Dead Crag Boar

### ISSUE THREAD

**Issue by iroflu** [FlamestrikeGG/Bugtracker-Flamestrike#40]
### Current Behavior:
The '[Dead Crag Boar](https://www.wowhead.com/npc=40939/dead-crag-boar)' is listed as faction 35. It is also unselectable/name doesn't show without GM mode.

### Expected behavior:
This npc should either not be here, or feign death. There are a few around, mixed in with what should be here ([Crag Boar](https://www.wowhead.com/classic/npc=1125/crag-boar)). This is the only living 'Crag Boar' that should be around here.

### How to reproduce the bug:
Go to the 'Grizzled Den' cave entrance just outside of Kharanos and see 4 to 5 (at least) 'Dead Crag Boars'.
The boars are both outside AND inside the cave.
They are visible without GM, but do not have a name above them, and without GM mode cannot be selected.

I circled the CORRECT boar in yellow, and the boars that are incorrectly spawned in green:
![friendlyboar](https://github.com/FlamestrikeGG/Bugtracker-Flamestrike/assets/7875502/6afed9cf-66af-44bc-b6a7-ef350bb7a4b5)
![boar2](https://github.com/FlamestrikeGG/Bugtracker-Flamestrike/assets/7875502/9f6b6524-1a04-4462-a71c-17cdcefd7f8a)
![b3](https://github.com/FlamestrikeGG/Bugtracker-Flamestrike/assets/7875502/26824d89-ec83-4e32-a97f-f0d8bbdd41e0)

**Comment by FlamestrikeGG** [comment]
@iroflu - Should be fixed now. Can you test and confirm that it works now?

**Comment by LKArthas** [comment]
Fixed
