### ISSUE TITLE
[Spell][Mage] Ignite spreading with Impact

### ISSUE THREAD

**Issue by Pocketerino** [FlamestrikeGG/Bugtracker-Flamestrike#49]
Current Behavior (The current behavior of the reported function):

Ignite spread with Impact onto nearby targets does not inherit the damage properly from the target that got hit with Impact, the duration seems to be correct. Living Bomb and Pyroblast DoT damage and duration are correct.

Expected behavior (The correct behavior of the reported function):

Impact should spread all of the mages DoT effect onto all nearby targets within 12 yards (except for LB, 3 target limit, this works properly), these DoTs should have the exact same duration and damage as the DoTs of the target Impact/Fire Blast was cast on, currently as i said, the duration of the spread Ignite seems correct but the damage is not, sometimes its higher by 30-40% compared to the original Ignite. 

How to reproduce the bug (How did this happen?):

1. Build an Ignite on a target with Impact up
2. Press Fire Blast
3. Look at the damage that Ignite is doing on secondary targets

**Comment by Greymane** [comment]
![image](https://github.com/FlamestrikeGG/Bugtracker-Flamestrike/assets/671155/efaea57c-5792-42aa-bae4-d69ad0c6fcaf)

Mechanic is now apparently fixed, will be pushing the change shortly, please note that if Fire blast crits and adds more ignite to the bank, that extra bank is currently not being carried over to the ignite-impact spread, is that intended or is that also another bug?
