### ISSUE TITLE
[Quest][Camp Narache] Feed of Evil

### ISSUE THREAD

**Issue by Kyyteo** [FlamestrikeGG/Bugtracker-Flamestrike#5]
Current Behavior (The current behavior of the reported function): Battle Boars will just stand around doing nothing, and don't react when troughs are lit ablaze. Troughs Stay ablaze, rather than going out.

Expected behavior (The correct behavior of the reported function): Battle Boars around the troughs are supposed to be feeding from the troughs, and when Adana's Torch is activated, the ones feeding are supposed to be lit ablaze, in which they run around at fast speed before quickly dying, giving you quest progress. Troughs should also reset after a few to allow the next player to do the quest.

How to reproduce the bug (How did this happen?): Take the quest, observe their behavior then try to light one of the troughs.

https://cata-shoot.tauri.hu/?item=49539
https://cata-shoot.tauri.hu/?quest=14461
https://youtu.be/6CblI7Lsuxw?t=48

**Comment by LKArthas** [comment]
Fixed
