### ISSUE TITLE
[Spell][Night Elf] Shadowmeld

### ISSUE THREAD

**Issue by Zafire** [FlamestrikeGG/Bugtracker-Flamestrike#51]
**Current Behavior (The current behavior of the reported function):** 
- Upon creating a night elf, shadowmeld is placed on bar slot 5. it should be placed on the same bar slot as all other races racials, which is "10" (bound to button "0")
- Casting Shadowmeld puts you into PvP mode.

**Expected behavior (The correct behavior of the reported function):** SM placed on bar slot 10, SM not activate PVP

**How to reproduce the bug (How did this happen?):** Create a Night Elf, cast Shadowmeld.

**Comment by Greymane** [comment]
![image](https://github.com/FlamestrikeGG/Bugtracker-Flamestrike/assets/671155/4f3f51ca-daef-4bd7-a1e4-95b614d4fa05)
Shadowmeld action button seems to be placed in the proper location when you create a NE.
