### ISSUE TITLE
[Spell][Warrior] Attack, Auto Attack

### ISSUE THREAD

**Issue by Zafire** [FlamestrikeGG/Bugtracker-Flamestrike#52]
**Current Behavior (The current behavior of the reported function):** Warriors start out with both "Auto Attack" and "Attack".
**Expected behavior (The correct behavior of the reported function):** They should only have "Auto Attack".
**How to reproduce the bug (How did this happen?):** Create Warrior.

**Comment by Greymane** [comment]
That's client side data, the spell is supposed to be there, will mark this one as invalid.
