### ISSUE TITLE
[Spell][Rogue] Rogue Trainers teach 2 versions of "Leather Specialization"

### ISSUE THREAD

**Issue by Zafire** [FlamestrikeGG/Bugtracker-Flamestrike#55]
**Current Behavior (The current behavior of the reported function):** 

![image](https://github.com/FlamestrikeGG/Bugtracker-Flamestrike/assets/18059881/ff795bae-7198-4d32-9d8b-be95a53c37ef)

Rogues can learn 2 versions of "Leather Specialization" at level 50. ( All traieners seem to be teaching these two spells.

**Expected behavior (The correct behavior of the reported function):** 

There should only be one version available

**How to reproduce the bug (How did this happen?):** 

Be a rogue and visit rogue trainer. (for example "Lord Tony Romano" in Stormwind)

**Comment by Greymane** [comment]
Some trainers have only one of them tho, lol 
![image](https://github.com/FlamestrikeGG/Bugtracker-Flamestrike/assets/671155/b485f737-2431-4893-9a3d-a4826de640af)
![image](https://github.com/FlamestrikeGG/Bugtracker-Flamestrike/assets/671155/f9600495-883f-4ad7-a530-1ca01122e1fc)
