### ISSUE TITLE
[General][NPC] Mobs doesn't leave combat in open world

### ISSUE THREAD

**Issue by Zafire** [FlamestrikeGG/Bugtracker-Flamestrike#56]
When you attack a creature and go to a "safe spot" where the mob can't reach you (no path found), it should leave combat after a while.

- Attack mobs here, run up the ramp then jump down. The mobs stand there forever and never reset if they can't reach you. (They SHOULD be able to reach you at this exact spot, but can't because of bad mmaps etc) - anyway they should reset if they can't reach you.
- Example: https://i.gyazo.com/47ff7d597c2923cb3fa2ea42b06f24fa.mp4
- .GPS: Map: 530 (Outland), Zone: 3430 (Eversong Woods), Area: 3662 (Commons Hall)
Phase 0 (NoNPhased), PhaseMask: 1
X: 9817.006836, Y: -6688.765625, Z: 18.975704 Orientation: 4.940509
grid[50,19], cell[3,3], InstanceID: 0
ZoneX: 44.695747, ZoneY: 37.299271
GroundZ: -0.697317, FloorZ: 18.975704 Have height data (Map: 1, VMap: 1)

- Teleport: .go c 9999

**Comment by FlamestrikeGG** [comment]
Please provide an example of a mob that does this @Zafire and your coordinates (.GPS), or even a video, so it can easily be reproduced
