### ISSUE TITLE
[General, NPC] Caster mobs will not chase you.

### ISSUE THREAD

**Issue by Zafire** [FlamestrikeGG/Bugtracker-Flamestrike#57]
If you LoS a caster mob, they will not chase you, just stand there and then return to their spawnpoint, still in combat with you.

- https://i.gyazo.com/d4254b10f832d801940b9d8919b0f306.mp4
- .go c 32955

Map: 530 (Outland), Zone: 3433 (Ghostlands), Area: 3514 (The Dead Scar)
Phase 0 (NoNPhased), PhaseMask: 1
X: 7894.391113, Y: -6626.692383, Z: 42.174698 Orientation: 1.273156
grid[46,19], cell[6,4], InstanceID: 0
ZoneX: 40.707859, ZoneY: 16.921591
GroundZ: 42.175785, FloorZ: 42.175785 Have height data (Map: 1, VMap: 1)

Attack mob: Deathcage Scryer, go out of its sight (behind a tree or whatever) and see how it stays there forever

**Comment by FlamestrikeGG** [comment]
Please provide an example of a mob that does this @Zafire and your coordinates (.GPS), or even a video, so it can easily be reproduced
