### ISSUE TITLE
[NPC] Armored Battleboars

### ISSUE THREAD

**Issue by Kyyteo** [FlamestrikeGG/Bugtracker-Flamestrike#6]
Current Behavior (The current behavior of the reported function): Battleboars just kind of stand around doing nothing

Expected behavior (The correct behavior of the reported function): Some Battleboars are supposed to be feeding on the nearby bones and in the nearby troughs. Not all of them of course but definitely some

How to reproduce the bug (How did this happen?): Observe the Boars behavior

https://cata-shoot.tauri.hu/?npc=36696
https://youtu.be/1_q1Wu49L1A?t=31

**Comment by LKArthas** [comment]
Fixed
