### ISSUE TITLE
[Quest] [Gilneas][Crash]  Sacrifices

### ISSUE THREAD

**Issue by TheRealestMcCoy** [FlamestrikeGG/Bugtracker-Flamestrike#61]
Accepting the worgen quest sacrifices the first time put me on the mount but couldn't complete the quest.

Ran back clicked horse again and it was crashing the server. Repeated multiple times

So i abandoned the quest to pick it back up and now it just spawns horse and still crashes 

https://cata-shoot.tauri.hu/?quest=14212

**Comment by LKArthas** [comment]
Server seems to not be updated quest has been fixed a few days ago
![WoWScrnShot_080423_004356](https://github.com/FlamestrikeGG/Bugtracker-Flamestrike/assets/1549829/f5c78ba3-f74c-4690-9af1-d224eeefc67c)
![WoWScrnShot_080423_004352](https://github.com/FlamestrikeGG/Bugtracker-Flamestrike/assets/1549829/923f14a9-fd6c-4ba0-ace5-11ee101cf80c)
![WoWScrnShot_080423_004237](https://github.com/FlamestrikeGG/Bugtracker-Flamestrike/assets/1549829/4e85ac42-817b-4918-b5ed-28dc248a9058)
![WoWScrnShot_080423_004230](https://github.com/FlamestrikeGG/Bugtracker-Flamestrike/assets/1549829/75d2824c-1399-400e-9f68-3b68ee23a988)
![WoWScrnShot_080423_004225](https://github.com/FlamestrikeGG/Bugtracker-Flamestrike/assets/1549829/0227077a-ee6f-4975-8cbd-e3470fcd4acb)

**Comment by LKArthas** [comment]
Try not to test worgens until all files are fully uploaded, since it might contain crashes
