### ISSUE TITLE
[Quest] [Deathknell] Recruitment

### ISSUE THREAD

**Issue by fraesia** [FlamestrikeGG/Bugtracker-Flamestrike#75]
- Current Behavior: Darnell is supposed to visually pick up the scarlet corpses, instead, the scarlet corpses stand up, and Darnell does an auto attack animation. He also does not carry any corpses. Minor Animation Bug.
- Expected Behavior: After interacting with a scarlet corpse, Darnell will pick up the corpses and follow you until the quest is completed.
- To Replicate: Start the quest recruitment, and proceed to where the corpses are. 

https://www.wowhead.com/quest=26800/recruitment

**Comment by LKArthas** [comment]
Fixed
