### ISSUE TITLE
[Quest] [Tirisfal Glades] Scourge on our Perimeter 

### ISSUE THREAD

**Issue by fraesia** [FlamestrikeGG/Bugtracker-Flamestrike#76]
- Current Behavior: After accepting the quest, Darnell will spawn and begin to follow the player around, doing nothing. He will continue to follow the player even if the player dies and rezzes. 
- Expected Behavior: Darnell is not involved with this quest whatsoever. He should despawn after Recruitment quest. The Player meets him only at the Assault at Rotbrain Encampment quest to start it. 
- To Replicate: If Darnell does not despawn after the Recruitment quest, the bug will persist. Try dying and he will be next to you at the spirit healer. 
https://www.wowhead.com/quest=26801/scourge-on-our-perimeter

**Comment by fraesia** [comment]
I managed to make him despawn after interacting with him at the end of Rotbrain Encampment quest but he respawned to follow again after I died.

**Comment by LKArthas** [comment]
Fixed
