### ISSUE TITLE
[Quest] [Tirisfal Glades] The Damned

### ISSUE THREAD

**Issue by fraesia** [FlamestrikeGG/Bugtracker-Flamestrike#77]
- Current Behavior: Like the issue with The Shadow Grave, . 4 Scavenger Paw (3265) and 4 Duskbat Wing (3264) is not detected by Executor Arren (1570).
- Expected Behavior: Executor Arren should allow you to complete the quest with the items in your inventory.
- To Replicate: Do the quest normally.
https://www.wowhead.com/quest=376/the-damned

**Comment by LKArthas** [comment]
Fixed
