### ISSUE TITLE
[Quest] [Darkshore] Multiple: Any quest with an item turn in.

### ISSUE THREAD

**Issue by CMDR-Nef** [FlamestrikeGG/Bugtracker-Flamestrike#78]
**Current Behavior:** 
Any quest requiring an item(s) to be turned in cannot be completed unless the player abandons and then reaccepts the quest.  If the player has the required amount of quest items in their inventory the quest giver's over head icon and quest turn in text will still be greyed out. If the player abandons the quest, the quest items are not deleted as expected. The player can then reaccept the quest and immediately turn it in as expected. 

**Expected Behavior:** 
To be able to complete the quest should the player have the required number of quest items.

**Steps to Reproduce:** 
Accept and attempt to complete any quest requiring an item turn in. 

**Additional Comments:**  
I've tried the following work arounds for this issue without success. I dropped the quest, deleted and recollected the items. I dropped the quest and spawned the items. I've talked to the quest givers while mounted, unmounted. I've logged out and back in. The only way to advance is to drop and retake the quest.

**Comment by Greymane** [comment]
@CMDR-Nef Can i get some quest id or name that i can test this? did some random questing in teldrassil (thinking it could be a server-wide problem) and they all worked fine.

**Comment by CMDR-Nef** [comment]
Sure, Probably the easiest would be either the "Buzzbox" series, starting with "Buzzbox 413" ID: 13521 obtained from Wizbang Cranktoggle at position: 7375.459961 -289.412994 6.241100. 

Or "The Boon of the Seas" ID: 13520 given by Serendia Oakwhisper. She's right beside the Lor'danel flight master at position: 7462.240234 -326.545990 8.207000. provided you have not completed her series of quests. 

You may need to complete "Thread from the Water" ID: 13522 given by Ranger Glynda Nal'Shea who paths around Lor'danel to see either of these quests.
