### ISSUE TITLE
[Quest][Tirisfal Glades] Escaped from Gilneas, Annihilate the Worgen

### ISSUE THREAD

**Issue by fraesia** [FlamestrikeGG/Bugtracker-Flamestrike#80]
Current Behaviour: Worgen Infiltrator does not spawn to kill the cursed darkhound (1458) attacking you. Thus, the quests cannot start.

Expected Behaviour: When attacking a Cursed Darkhound, a Worgen Infiltrator will spawn to kill it for you, enter dialogue, despawn and automatically give the Escaped from Gilneas (24992) quest. Which starts the second quest, Annihilate the Worgen (24993) when reporting to Executor Zygand (1515).

Replicate: Get in combat with any Cursed Darkhound. I have tried to spawn the Worgen for 30-45 minutes, to no avail.

**Comment by LKArthas** [comment]
Fixed
