### ISSUE TITLE
[Quest] [Ebon Hold] Battle for Ebon Hold

### ISSUE THREAD

**Issue by fraesia** [FlamestrikeGG/Bugtracker-Flamestrike#87]
Current Behaviour: Knights of the Ebon Blade (31094) in front of Mograine do not move or attack enemies with you. 

Expected Behaviour: After accepting the quest "The Battle For The Ebon Hold" (13166), you will fight along with the knights to defeat patchwerk etc.

To Replicate: Go to Morgraine (31084) and accept the quest.

**Comment by fraesia** [comment]
managed to fix with a re-log, issue is fixed

**Comment by LKArthas** [comment]
Fixed
